Algoritmo "ParOuImpar"

Var

    numero : inteiro


Inicio
      para numero de 1 ate 5 faca
           escreva("Escreva um número: ")
           leia(numero)
      fimpara
      
      para numero de 1 ate 5 faca
          se numero mod 2 = 0 entao
              escreva("O número ", numero, " é par!")
          senao
              escreva("O número ", numero, " é ímpar!")
          fimse
      fimpara
Fimalgoritmo